carrinho/urls.py
app_name = "carrinho"

from carrinho import views
from django.urls import path, include

urlpatterns = [
    path('',views.lista_produto, name = "lista_produtos"),

    path('atualiza_carrinho/', views.atualiza_carrinho, name = "atualiza_carrinho"),

    #--------------------------------------------------------
    # carrinho/fruta
    # carrinho/grão
    path('<slug:slug_da_categoria>/', views.lista_produto, name = "lista_produtos_por_categoria"),

    #--------------------------------------------------------
    # carrinho/11/laranja
    # carrinho/21/arroz
    path('<int:id>/<slug:slug_do_produto>/', views.exibe_produto, name = "exibe_produto")
]

produto/urls.py
from django.urls import path

from produto import views

app_name = 'produto'

urlpatterns = [
    path('lista_produto/', views.lista_produto, name='lista_produto')
]

projeto/urls.py
from os import stat
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from projeto import views, settings
from django.conf.urls.static import static

urlpatterns = [
    path('', lambda request : redirect("fornecedor/")),
    path('carrinho/', include('carrinho.urls')),
    path('produto/', include('produto.urls')),
    path('admin/', admin.site.urls),
    path('fornecedor/', include('fornecedor.urls'))
]

#----------------------------------------------------------
# Para o upload de imagens
if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )


#     Como acessar a página index.html do projeto:
#     http://127.0.0.1:8000/
#
#     Como acessar a página index.html de produto:
#     http://127.0.0.1:8000/produto/

carrinho/models.py
from django.db import models

# Create your models here.

carrinho/forms.py
from django import forms

class QuantidadeForm( forms.Form ):

    #------------------------------------------------------------
    # forms.HiddenInput torna produto_id invisivel para o usuário
    produto_id = forms.CharField( widget = forms.HiddenInput() ,
    max_length = 4 , required = True )


    quantidade = forms.IntegerField( 
        min_value = 0,
        max_value = 99,
        widget = forms.TextInput( attrs = { 'class' : 'form-control btn-secondary bg-secondary quantidade' ,
                                            'width': '70px',
                                            'readonly': 'readonly'} ),
        required  = True )

carrinho/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, get_object_or_404, HttpResponse
from produto.models import Produto
from categoria.models import Categoria
from carrinho.carrinho import Carrinho
from carrinho.forms import QuantidadeForm
# Create your views here.

def lista_produto( request , slug_da_categoria = None ):
    
    cat = None
    produtos = Produto.objects.filter( disponivel = True ).order_by('nome')
    if not ( slug_da_categoria is None ):
        cat = get_object_or_404( Categoria , slug = slug_da_categoria )
        produtos = produtos.filter( categoria = cat )
    
    categorias = Categoria.objects.all().order_by('nome')
    carr       = Carrinho( request )
    lst_form   = []
    for produto in produtos:
        qtd = carr.get_quantidade( produto.id )
        lst_form.append( QuantidadeForm( initial = {'quantidade':qtd , 'produto_id':produto.id}) )
    
    listas = zip( produtos , lst_form )
    d = dict()
    d['categorias'] = categorias
    d['listas']     = listas
    d['cat']        = cat

    return render( request, 'carrinho/lista_produtos.html', d )

def exibe_produto( request , id , slug_do_produto ):

    #----------------------------------------------
    # slug do produto na real não será usado para nada
    # so ta ai para os motores de busca

    produto = get_object_or_404( Produto , id = id )
    return render( request , 'carrinho/exibe_produto.html', { "produto":produto } )
    
def atualiza_carrinho( request ):
    
    form = QuantidadeForm( request.POST )
    if form.is_valid():
        
        produto_id = form.cleaned_data[ 'produto_id' ]
        quantidade = form.cleaned_data[ 'quantidade' ]

        carrinho = Carrinho( request )
        if quantidade == 0:
            carrinho.remover( produto_id )
            preco_total = 0
        else:
            carrinho.atualizar( produto_id , quantidade )
            preco_total = carrinho.get_preco_total( produto_id )
        
        qtd = carrinho.get_qtd_total()
        prec = carrinho.get_gasto_total()

        print( "****** id do produto: {}".format( produto_id ) )
        print( "****** qtd do produto: {}".format( quantidade ) )
        print( "****** preco do produto: {}".format( preco_total ) )

        return JsonResponse( {'qtd':qtd, 'gasto':prec })
    else:
        raise ValueError( "OOPS! Ocorreu algum erro.")

carrinho/templates/carrinho/exibe_produto.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Vitrine de {{ produto.nome }}
{% endblock %}

{% block corpo %}
    <div class = "row" >
        <div class = "col-4">
            <img src = "{% static 'images/produtos/' %}{{ produto.imagem }}"
            style = "width: 100%;" >
        </div>
        <div class = "col-8">
            <div class = "row">
                <div class = "col-3 font-weight-bold">Nome</div>
                <div class = "col-9">{{ produto.nome }}</div>
            </div>
            <div class = "row">
                <div class = "col-3 font-weight-bold">Descrição</div>
                <div class = "col-9">{{ produto.descricao }}</div>
            </div>
            <div class = "row">
                <div class = "col-3 font-weight-bold">Preço</div>
                <div class = "col-9"> R${{ produto.preco }}</div>
            </div>
        </div>
    </div>
{% endblock %}

carrinho/templates/carrinho/lista_produtos.html
{% extends 'base.html' %}

{% load static %}

{% block titulo %}
   Lista de Produtos
{% endblock %}

{% block corpo %}
    <div class = "row" >
        <!-- Seletor de categorias ############################## -->
        <div class = "col-lg-2">
            <div class = "nav flex-column nav-pills">
                <a class = "nav-link {% if not cat %}active{% endif %}" href = "/">Todos</a>
                {% for catg in categorias %}
                    <a class = "nav-link {% if catg.nome == cat.nome %}active{% endif %}" 
                    href = "{{ catg.get_absolute_url }}">{{ catg.nome }}</a>
                {% endfor %}
            </div>
        </div>

        <!-- grade de produtos ################################## -->
        <div class = "col-lg-10">
            <div class = "row">
                <h5> {% if cat %}{{ cat.nome }}{% else %}Todos{% endif %}</h5>
            </div>
            <div class = "row", id = "prod_cards" >
                {%for prod , form in listas %}
                <div class = "col-5 col-lg-2 mx-1 my-1 px-0">

                    <div class="card text-center mr-2">
                        <img class="card-img-top w-100" 
                        src="{% static 'images/produtos/' %}{{ prod.imagem }}" 
                        alt = "{{ prod.nome }}">

                        <div class="card-body">
                        <h5 class="card-title">
                            <a href = "{{ prod.get_absolute_url }}">
                                {{ prod.nome }}
                            </a>
                        </h5>
                        <p class="card-text">{{ prod.descricao }}</p>
                        <p class="card-text font-weight-bold" style = "color: #dc3545;">R${{ prod.preco }}</p>
                        </div>

                        <div class = "card-footer border-0 mb-1">
                            <form class  = "form-inline"
                                  style  = "{% if form.quantidade.value == 0 %} display : none {% endif %}"
                                  method = "POST" novalidate
                                  action = "{% url 'carrinho:atualiza_carrinho' %}">
                                {% csrf_token %}
                                {{ form.produto_id }}
                                <div class="input-group w-100">

                                    <div class="input-group-prepend">
                                      <input type = "button" class = "btn btn-secondary menos" value="-">
                                    </div>

                                    {{ form.quantidade }}

                                    <div class="input-group-append">
                                        <input type = "button" class = "btn btn-secondary mais" value="+">
                                    </div>

                                </div>

                            </form>
                            <input type = "button" class = "btn btn-primary comprar w-100"
                                    style = "{% if form.quantidade.value > 0 %} display : none {% endif %}"
                                    value = "Comprar">
                        </div>
                    </div>
                </div>,
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

{% block domready %}
{% endblock %}