produto/urls.py
from django.urls import path

from produto import views

app_name = 'produto'

urlpatterns = [
    path('lista_produto/', views.lista_produto, name='lista_produto')
]

projeto/urls.py
from os import stat
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from projeto import views, settings
from django.conf.urls.static import static

urlpatterns = [
    path('', lambda request : redirect("fornecedor/")),
    path('carrinho/', include('carrinho.urls')),
    path('produto/', include('produto.urls')),
    path('admin/', admin.site.urls),
    path('fornecedor/', include('fornecedor.urls'))
]

#----------------------------------------------------------
# Para o upload de imagens
if settings.DEBUG:
    urlpatterns += static( settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )


#     Como acessar a página index.html do projeto:
#     http://127.0.0.1:8000/
#
#     Como acessar a página index.html de produto:
#     http://127.0.0.1:8000/produto/

templates/base.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-ui.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/dropzone.css' %}" />
    <title>{% block titulo %}Hortifruti{% endblock %}</title>
    <style>
        {% block estilo %}

        {% endblock %}
    </style>
</head>

<body class="barra">

    <div class="container mt-3 mb-2">
        <div class="row">
            <div class="col-3">
                <a class="d-none d-md-block" style="text-decoration: none; font-size: 16px" href="#">
                    <img src="{% static 'images/hortifruti-icon.png' %}" style="width: 70px" alt="Hortifruti">
                    Hortifruti
                </a>
                <a class="d-block d-md-none" style="text-decoration: none; font-size: 16px" href="#">
                    <img src="{% static 'images/hortifruti-icon.png' %}" style="width: 70px" alt="Hortifruti">
                </a>
            </div>
            <div class="col-6 d-flex align-items-center justify-content-center">
                <div class="d-none d-lg-block">
                    <div class="d-flex justify-content-center">
                        Já é cadastrado? Faça seu<a style="text-decoration: none" class="pl-1" href="#">login!</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a style="text-decoration: none" href="#">Cadastre-se aqui.</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a style="text-decoration: none" href="{% url 'produto:lista_produto' %}">Lista Produtos</a>
                    </div>
                </div>
                <div class="d-block d-lg-none">
                    <div class="d-flex justify-content-center">
                        Já é cadastrado?
                    </div>
                    <div class="d-flex justify-content-center">
                        Faça seu<a style="text-decoration: none" class="pl-1" href="#">login!</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a style="text-decoration: none" href="#">Cadastre-se aqui.</a>
                    </div>
                    <div class="d-flex justify-content-center">
                        <a style="text-decoration: none" href="{% url 'produto:lista_produto' %}">Lista Produtos</a>
                    </div>
                </div>
            </div>
            <div class="col-3 d-flex justify-content-end align-items-center">
                <div class="d-none d-sm-block">
                    <a style="text-decoration: none" href="#">
                        <img src="{% static 'images/carrinho.png' %}" style="width: 35px" alt="Carrinho">
                        Carrinho
                    </a>
                    <div id = 'total-1' class = "d-flex justify-content-center">
                        {% if qtd == 1 %}
                            {{ qtd }} item - R$ {{ gasto | floatformat:2 | intcomma }}
                        {% else %}
                            {{ qtd }} itens - R$ {{ gasto | floatformat:2 | intcomma }}
                        {% endif %}
                    </div>
                </div>
                <div class="d-block d-sm-none">
                    <a style="text-decoration: none" href="#">
                        <img src="{% static 'images/carrinho.png' %}" style="width: 35px" alt="Carrinho">
                    </a>
                    <div id = 'total-1' class = "d-flex justify-content-center">
                        {% if qtd == 1 %}
                            {{ qtd }} item - R$ {{ gasto | floatformat:2 | intcomma }}
                        {% else %}
                            {{ qtd }} itens - R$ {{ gasto | floatformat:2 | intcomma }}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div style="padding: 3px" class="bg-danger mb-3"></div>

    <div id="container" class="container">
        {% block corpo %}

        {% endblock %}
    </div>

    {% block rodape %}
        <div class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3 col-sm-6">
                        <h6>Institucional</h6>
                        <ul class="list-unstyled">
                            <li><a style="text-decoration: none" href="#">Política de pagamento</a></li>
                            <li><a style="text-decoration: none" href="#">Política de troca</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-sm-6">
                        <h6>Atendimento</h6>
                        <ul class="list-unstyled">
                            <li><a style="text-decoration: none" href="#">Fale conosco</a></li>
                            <li><a style="text-decoration: none" href="#">Prazo de entrega</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-sm-6">
                        <h6>Nossa Empresa</h6>
                        <ul class="list-unstyled">
                            <li><a style="text-decoration: none" href="#">Quem somos</a></li>
                            <li><a style="text-decoration: none" href="#">FAQ</a></li>
                            <li><a style="text-decoration: none" href="/fornecedor/lista_fornecedor">Fornecedores</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-sm-6">
                        <h6>News Letter</h6>
                        <form class="form-inline">
                            <label class="sr-only" for="email">Email</label>
                            <input type="text" name="email" id="email"
                                   class="form-control form-control-sm mr-2 mb-2"
                                   placeholder="Seu email">
                            <button type="submit" class="btn btn-sm btn-primary mb-2">Enviar</button>
                        </form>
                    </div>

                </div>
            </div>
        </div>
    {% endblock %}

    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.js' %}"></script>
    <script src="{% static 'js/popper.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/dropzone.js' %}"></script>
    {% block domready %}
    {% endblock %}
    
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block corpo %}

{% endblock %}